### PR TITLE
Fix @solnic's age

### PR DESCRIPTION
**Pull request by blashca**
Hi,

This is officially my first pull request ever :smile_cat: 
In the future I'll try to make more usefull contribution, but for now this is it.

### CODE REVIEW

**Comment by blashca** [comment]
LOL, wrong calculation, sorry.
Give me a sec. fix is on the way :)

**Comment by blashca** [comment]
Do you prefer these commits to be squashed together? ;)

**Comment by solnic** [comment]
Hah! I'm honored :) Merging in. Thanks Blanka and it's really really nice to see you here!

**Comment by blashca** [comment]
Glad I could help a bit :)

**Pull request merged**
